version: '3.1'

services:

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - 2717:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: darpa
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: mongo-dash
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: darpa
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://darpa:example@mongo:27017/
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-dash.rule=Host(`mongo-dash.home.pi`)"
      - "traefik.http.routers.mongo-dash.entrypoints=web"
      - "traefik.http.services.mongo-dash.loadbalancer.server.port=8081"
      - "traefik.http.routers.mongo-dash.service=ngnix"

networks:
  traefik:
    name: traefik_default