services:
  excalidraw:
    container_name: excalidraw
    image: 'excalidraw:latest'
    restart: unless-stopped
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.excalidraw.rule=Host(`excalidraw.localhost`)"
      - "traefik.http.routers.excalidraw.entrypoints=web"
      - "traefik.http.services.excalidraw.loadbalancer.server.port=80"
      - "traefik.http.routers.excalidraw.service=excalidraw"

networks:
  traefik:
    name: traefik_default