services:
  postgres:
    image: postgres:13.4-alpine
    restart: unless-stopped

    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=prestabooks_db
    networks:
      - traefik

  pgadmin:
    image: dpage/pgadmin4:5.6
    restart: unless-stopped

    environment:
      - PGADMIN_DEFAULT_EMAIL=darpa@darpa.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    links:
      - postgres:postgres
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin.rule=Host(`pgadmin.localhost`)

networks:
  traefik:
    name: traefik_default
