services:
  postgres:
    image: postgres:13.4-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=prestabooks_db
    networks:
      - traefik
    labels:
      - traefik.enable=true

  pgadmin:
    image: dpage/pgadmin4:5.6
    environment:
      - PGADMIN_DEFAULT_EMAIL=darpa@darpa.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
    links:
      - postgres:postgres
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.pgadmin=Host(`pgadmin.home.com`)

networks:
  traefik:
    name: traefik_default
